language: generic
sudo: required
services:
    - docker
before_install:
    - docker build -t shklnrj/ReactDockerProd -f Dockerfile.dev .
script:
    - docker run -e CI=true shklnrj/ReactDockerProd yarn test --watchAll=false --coverage
